// Export all components for easier imports
export { default as Button } from './Button'
export { default as Container } from './Container'
export { default as Section } from './Section'
export { default as SectionHeader } from './SectionHeader'
export { default as Header } from './Header'
export { default as Footer } from './Footer'
export { default as TestimonialCard } from './TestimonialCard'
export { default as FeatureCard } from './FeatureCard'
export { default as ServiceCard } from './ServiceCard'
export { default as BlogCard } from './BlogCard'
export { default as ProcessStep } from './ProcessStep'
export { default as CTABanner } from './CTABanner'
export { default as ContactForm } from './ContactForm'
export { default as NewsletterForm } from './NewsletterForm'
export { default as CalendarEmbed } from './CalendarEmbed'
export { default as OptInForm } from './OptInForm'
export { default as StickyMobileCTA } from './StickyMobileCTA'

// Export section components
export { default as HeroSection } from './sections/HeroSection'
export { default as ProblemSection } from './sections/ProblemSection'
export { default as TransformationSection } from './sections/TransformationSection'
export { default as ProcessSection } from './sections/ProcessSection'
export { default as TestimonialsSection } from './sections/TestimonialsSection'
export { default as OffersSection } from './sections/OffersSection'
export { default as LeadMagnetSection } from './sections/LeadMagnetSection'
export { default as AboutSection } from './sections/AboutSection'
export { default as FAQSection } from './sections/FAQSection'
export { default as FinalCTASection } from './sections/FinalCTASection'

